<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Valency.Shell.Core\Valency.Shell.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Properties\Resources.resx" />
    <EmbeddedResource Include="Properties\Resources.en.resx">
      <DependentUpon>Resources.resx</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Serilog" Version="4.4.0" />
  </ItemGroup>

</Project>
